### ISSUE TITLE
support the new .conda package format

### ISSUE THREAD

**Issue by FaustinCarter** [conda-incubator/conda-mirror#10]
Since conda 4.7, there is a new package format (.conda) in addition to the legacy format (.tar.bz2). See note here: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#conda-file-format. It would be great to add support for these. Suggested form is a flag that allows for only .conda, only .tar.bz2, or both.

**Comment by analog-cbarber** [comment]
Seems like we only need to add .conda to the filter in `_list_conda_packages`.

BTW, if I understand the code correctly, it looks like it is currently going to download
both .tar.bz2 and .conda packages but will only keep the .tar.bz2 ones, so even if you
only wanted the .tar.bz2 versions, you would still pay the price of downloading both.

**Comment by analog-cbarber** [comment]
It does not seem like this would be hard, but I cannot find any repos that actually have .conda packages in their repodata.json files. I do see some .conda packages in my local conda pkgs cache directory that appear to have come from https://repo.anaconda.com/pkgs/main, but I don't see them in that index file.

Are .conda files listed in something other than repodata.json?

**Comment by asilenzi** [comment]
Hi All,

I submitted a PR for this issue. in the last days conda-forge switched to the `.conda` extension and I suspect this is quite severe.
