### ISSUE TITLE
Increase download speed

### ISSUE THREAD

**Issue by analog-cbarber** [conda-incubator/conda-mirror#28]
The code currently uses a chunk size of 1024 bytes. Consider using a much larger size (1MB)

Also consider using a session.

See https://stackoverflow.com/questions/23369625/ideal-chunk-size-for-python-requests

**Comment by analog-cbarber** [comment]
Playing with this a bit I really don't see any real performance difference when I change the chunk size on my machine and network, but using a common `requests.Session` object can make a big difference. I saw something like a 30% to 400% speedup when using a session. I think it may be a bigger win when packages are small.

**Comment by analog-cbarber** [comment]
Fixed in https://github.com/analog-garage/conda-mirror/tree/ag-faster-download

**Comment by xhochy** [comment]
This sounds very useful as this should get the TLS connection alive. This is probably the major cost for very small packages.
