### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by analog-cbarber** [conda-incubator/conda-mirror#34]
There haven't been any commits for a long time and there are three old pending pull requests.

If pull requests aren't going to be merged, then there is really no point in going to the trouble of submitting them and I might as well just work independently on my own fork.

**Comment by xhochy** [comment]
This is still maintained and I will happily review pull requests.

We probably need to port CI first to Github Actions so that we get ✅ on PRs again.

**Comment by analog-cbarber** [comment]
In that case, would it be ok to submit a single PR with multiple issues?

**Comment by xhochy** [comment]
I would prefer multiple ones. The larger the PR the harder it will be to review and merge.
